// Code generated by tablegen. DO NOT EDIT.

package tables

import (
	"database/sql"
	"fmt"

	"github.com/hansjlachmann/openerp/src/foundation/types"
)

// PaymentTerms represents Table 3: Payment Terms
type PaymentTerms struct {
	code types.Code `db:"code,pk"`
	description types.Text `db:"description"`
	active bool `db:"active"`
}

const PaymentTermsTableID = 3
const PaymentTermsTableName = "Payment Terms"

// GetTableID returns the table ID (for Object Registry)
func (t *PaymentTerms) GetTableID() int {
	return PaymentTermsTableID
}

// GetTableName returns the table name
func (t *PaymentTerms) GetTableName() string {
	return PaymentTermsTableName
}

// GetTableSchema returns the CREATE TABLE schema
func (t *PaymentTerms) GetTableSchema() string {
	return GetPaymentTermsTableSchema()
}

// GetPaymentTermsTableSchema returns the SQLite schema
func GetPaymentTermsTableSchema() string {
	return `
		code TEXT(10) PRIMARY KEY,
		description TEXT(30),
		active INTEGER DEFAULT 1
	`
}

// CreateTable creates the Payment Terms table for the specified company
func (t *PaymentTerms) CreateTable(db *sql.DB, company string) error {
	tableName := fmt.Sprintf("%s$%s", company, PaymentTermsTableName)
	schema := GetPaymentTermsTableSchema()

	createSQL := fmt.Sprintf(`CREATE TABLE IF NOT EXISTS "%s" (%s)`, tableName, schema)
	_, err := db.Exec(createSQL)
	if err != nil {
		return fmt.Errorf("failed to create Payment Terms table: %w", err)
	}

	return nil
}

// Code returns the code field
func (t *PaymentTerms) Code() types.Code {
	return t.code
}

// SetCode sets the code field
func (t *PaymentTerms) SetCode(value types.Code) error {
	if value.IsEmpty() {
		return fmt.Errorf("code cannot be empty")
	}
	if len(value) > 10 {
		return fmt.Errorf("code cannot exceed 10 characters")
	}
	t.code = value
	return nil
}

// Description returns the description field
func (t *PaymentTerms) Description() types.Text {
	return t.description
}

// SetDescription sets the description field
func (t *PaymentTerms) SetDescription(value types.Text) error {
	if len(value) > 30 {
		return fmt.Errorf("description cannot exceed 30 characters")
	}
	t.description = value
	return nil
}

// Active returns the active field
func (t *PaymentTerms) Active() bool {
	return t.active
}

// SetActive sets the active field
func (t *PaymentTerms) SetActive(value bool) error {
	t.active = value
	return nil
}
