// Code generated by tablegen. DO NOT EDIT.

package tables

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/hansjlachmann/openerp/src/foundation/types"
)

// PaymentTerms represents Table 3: Payment Terms
type PaymentTerms struct {
	code types.Code `db:"code,pk"`
	description types.Text `db:"description"`
	dueDateCalculation string `db:"due_date_calculation"`
	discountDateCalc string `db:"discount_date_calculation"`
	discountPct float64 `db:"discount_pct"`
	calcPmtDiscOnCrMemo bool `db:"calc_pmt_disc_on_cr_memos"`
	lastModifiedDateTime time.Time `db:"last_modified_date_time"`
}

const PaymentTermsTableID = 3
const PaymentTermsTableName = "Payment Terms"

// GetTableID returns the table ID (for Object Registry)
func (t *PaymentTerms) GetTableID() int {
	return PaymentTermsTableID
}

// GetTableName returns the table name
func (t *PaymentTerms) GetTableName() string {
	return PaymentTermsTableName
}

// GetTableSchema returns the CREATE TABLE schema
func (t *PaymentTerms) GetTableSchema() string {
	return GetPaymentTermsTableSchema()
}

// GetPaymentTermsTableSchema returns the SQLite schema
func GetPaymentTermsTableSchema() string {
	return `
		code TEXT(10) PRIMARY KEY,
		description TEXT(100),
		due_date_calculation TEXT,
		discount_date_calculation TEXT,
		discount_pct REAL CHECK (discount_pct >= 0 AND discount_pct <= 100),
		calc_pmt_disc_on_cr_memos INTEGER,
		last_modified_date_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
	`
}

// CreateTable creates the Payment Terms table for the specified company
func (t *PaymentTerms) CreateTable(db *sql.DB, company string) error {
	tableName := fmt.Sprintf("%s$%s", company, PaymentTermsTableName)
	schema := GetPaymentTermsTableSchema()

	createSQL := fmt.Sprintf(`CREATE TABLE IF NOT EXISTS "%s" (%s)`, tableName, schema)
	_, err := db.Exec(createSQL)
	if err != nil {
		return fmt.Errorf("failed to create Payment Terms table: %w", err)
	}

	return nil
}

// Code returns the code field
func (t *PaymentTerms) Code() types.Code {
	return t.code
}

// SetCode sets the code field
func (t *PaymentTerms) SetCode(value types.Code) error {
	if value.IsEmpty() {
		return fmt.Errorf("code cannot be empty")
	}
	if len(value) > 10 {
		return fmt.Errorf("code cannot exceed 10 characters")
	}
	t.code = value
	return nil
}

// Description returns the description field
func (t *PaymentTerms) Description() types.Text {
	return t.description
}

// SetDescription sets the description field
func (t *PaymentTerms) SetDescription(value types.Text) error {
	if len(value) > 100 {
		return fmt.Errorf("description cannot exceed 100 characters")
	}
	t.description = value
	return nil
}

// DueDateCalculation returns the dueDateCalculation field
func (t *PaymentTerms) DueDateCalculation() string {
	return t.dueDateCalculation
}

// SetDueDateCalculation sets the dueDateCalculation field
func (t *PaymentTerms) SetDueDateCalculation(value string) error {
	t.dueDateCalculation = value
	return nil
}

// DiscountDateCalc returns the discountDateCalc field
func (t *PaymentTerms) DiscountDateCalc() string {
	return t.discountDateCalc
}

// SetDiscountDateCalc sets the discountDateCalc field
func (t *PaymentTerms) SetDiscountDateCalc(value string) error {
	t.discountDateCalc = value
	return nil
}

// DiscountPct returns the discountPct field
func (t *PaymentTerms) DiscountPct() float64 {
	return t.discountPct
}

// SetDiscountPct sets the discountPct field
func (t *PaymentTerms) SetDiscountPct(value float64) error {
	if value < 0 || value > 100 {
		return fmt.Errorf("discountPct must be between 0 and 100")
	}
	t.discountPct = value
	return nil
}

// CalcPmtDiscOnCrMemo returns the calcPmtDiscOnCrMemo field
func (t *PaymentTerms) CalcPmtDiscOnCrMemo() bool {
	return t.calcPmtDiscOnCrMemo
}

// SetCalcPmtDiscOnCrMemo sets the calcPmtDiscOnCrMemo field
func (t *PaymentTerms) SetCalcPmtDiscOnCrMemo(value bool) error {
	t.calcPmtDiscOnCrMemo = value
	return nil
}

// LastModifiedDateTime returns the lastModifiedDateTime field
func (t *PaymentTerms) LastModifiedDateTime() time.Time {
	return t.lastModifiedDateTime
}

// SetLastModifiedDateTime sets the lastModifiedDateTime field
func (t *PaymentTerms) SetLastModifiedDateTime(value time.Time) error {
	t.lastModifiedDateTime = value
	return nil
}
